apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myns12

secretGenerator:
- name: mysql-pass12
  literals:
  - password=mysql@12345

resources:
- namespace12.yml
- efs-provisioner12.yml
- rbac12.yml
- storage_class12.yml
- mysql12.yml
- wordpress12.yml