apiVersion: v1
kind: Service   #Creating service of type CLusterIP
metadata:
  name: database112
  labels:
    app: database1
  namespace: myns
spec:
  ports:
    - port: 3306
  selector:
    app: database1
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: database112
  labels:
    app: database1
  namespace: myns12
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database1
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database1
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql12
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: "webpage"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage12
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage12
        persistentVolumeClaim:
          claimName: efs-mysql12 #claim volume from PVC
