apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nfs-provisioner-role-binding12
subjects:
  - kind: ServiceAccount
    name: default
    namespace: myns12
roleRef:
  kind: ClusterRole
  name: cluster-admin
  
  apiGroup: rbac.authorization.k8s.io